import { Geist, Geist_Mono, Shrikhand } from "next/font/google";
import "./globals.css";
import "./styles.css";
import {
	faHandshakeAngle,
	faUtensils,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { cookies } from "next/headers";
import Link from "next/link";
import PropTypes from "prop-types";
import Header from "@/components/Header/Header";
import FavoritesProvider from "./FavoritesProvider.jsx";
import styles from "./layout.module.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const shrikhand = Shrikhand({
	weight: "400",
	variable: "--font-shrikhand",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
	// Lecture du cookie côté server
	const cookieStore = await cookies();
	const favoritesCookie = cookieStore.get("favorites")?.value;
	let initialFavorites = {};
	if (favoritesCookie) {
		try {
			initialFavorites = JSON.parse(decodeURIComponent(favoritesCookie));
		} catch (e) {
			initialFavorites = {};
			console.error(
				"Erreur lors de la lecture des favoris depuis le cookie :",
				e,
			);
		}
	}
	return (
		<html lang="fr">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${shrikhand.variable}`}
			>
				<FavoritesProvider initialFavorites={initialFavorites}>
					<div className={styles.page}>
						<Header />

						<main className={styles.mainContent}>
							<div className={styles.contentWrapper}>{children}</div>
						</main>

						<footer className={styles.footer}>
							<nav>
								<a href="/proposer-restaurant" className={styles.footerLink}>
									<FontAwesomeIcon
										icon={faUtensils}
										className={styles.footerIcon}
									/>
									Proposer un restaurant
								</a>
								<a href="/devenir-partenaire" className={styles.footerLink}>
									<FontAwesomeIcon
										icon={faHandshakeAngle}
										className={styles.footerIcon}
									/>
									Devenir partenaire
								</a>
								<a href="/mentions-legales">Mentions légales</a>
								<a href="/contact">Contact</a>
							</nav>
							<Link href="/" className={styles.footerLogo}>
								ohmyfood
							</Link>
						</footer>
					</div>
				</FavoritesProvider>
			</body>
		</html>
	);
}

RootLayout.propTypes = {
	children: PropTypes.node.isRequired,
};
